Foreground true
LogTime true
LogClean false
LogSyslog false
LogVerbose false
LocalSocket /tmp/clamd.sock
LocalSocketMode 660
FixStaleSocket true
User scanner
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
MaxThreads 2
MaxConnectionQueueLength 20
ReadTimeout 30
CommandReadTimeout 5
SendBufTimeout 30
StreamMaxLength 25M
MaxFileSize 25M
MaxScanSize 30M
MaxRecursion 12
MaxFiles 1000
ScanPDF true
