import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {createApp} from '../../src/http/app.js';
import {RoseRocketClient} from '../../src/tms/rose-rocket.js';
const rose=vi.hoisted(()=>({role:'owner',row:null as null|{org_id:string},lastWrite:null as any}));
const mocks=vi.hoisted(()=>({isAdmin:false,enabled:true,guideCompletedAt:null as string|null,legalAcceptedAt:'2026-09-12T18:00:00.000Z' as string|null,createUser:vi.fn(),generateLink:vi.fn(),getUser:vi.fn(),refreshSession:vi.fn(),otp:vi.fn(),from:vi.fn(),rpc:vi.fn(),retrieveCheckout:vi.fn(),retrieveSubscription:vi.fn(),sendSecurityEmail:vi.fn(),answerPortalSupport:vi.fn(),notifySupportRequest:vi.fn(),notifyLeadFunnel:vi.fn(),notifyOperationalError:vi.fn(),query:{select:vi.fn(),eq:vi.fn(),gte:vi.fn(),order:vi.fn(),range:vi.fn(),maybeSingle:vi.fn()}}));
vi.mock('@supabase/supabase-js',()=>({createClient:()=>({auth:{getUser:mocks.getUser,refreshSession:mocks.refreshSession,signInWithOtp:mocks.otp}})}));
vi.mock('../../src/config/supabase.js',()=>({timedFetch:globalThis.fetch,getSupabaseClient:()=>({from:mocks.from,rpc:mocks.rpc,auth:{admin:{createUser:mocks.createUser,generateLink:mocks.generateLink}}})}));
vi.mock('../../src/billing/stripe.js',()=>({retrieveCheckoutSession:mocks.retrieveCheckout,retrieveSubscription:mocks.retrieveSubscription,applyRetentionDiscount:vi.fn(),cancelSubscriptionAtPeriodEnd:vi.fn(),createBillingPortalSession:vi.fn(),pauseSubscriptionOneMonth:vi.fn()}));
vi.mock('../../src/notifications/security.sender.js',()=>({sendSecurityEmail:mocks.sendSecurityEmail}));
vi.mock('../../src/notifications/google-chat.sender.js',()=>({notifySupportRequest:mocks.notifySupportRequest,notifyLeadFunnel:mocks.notifyLeadFunnel,notifyOperationalError:mocks.notifyOperationalError}));
vi.mock('../../src/free-audit/support.js',()=>({answerPortalSupport:mocks.answerPortalSupport}));
const tenant='11111111-1111-4111-8111-111111111111';const other='22222222-2222-4222-8222-222222222222';
let server:ReturnType<typeof createApp>,base:string;
beforeEach(async()=>{
 rose.role='owner';rose.row=null;rose.lastWrite=null;
 vi.resetAllMocks();mocks.isAdmin=false;mocks.enabled=true;mocks.guideCompletedAt=null;mocks.legalAcceptedAt='2026-09-12T18:00:00.000Z';vi.stubEnv('PORTAL_URL','https://portal.example.com');vi.stubEnv('SUPABASE_ANON_KEY','public-key');vi.stubEnv('SUPABASE_URL','https://example.supabase.co');
 mocks.getUser.mockResolvedValue({data:{user:{id:'user-1',email:'client@example.com'}},error:null});
 mocks.refreshSession.mockResolvedValue({data:{user:null,session:null},error:{message:'invalid refresh token'}});
 mocks.retrieveSubscription.mockResolvedValue({id:'sub_1',status:'active',customer:'cus_1',trial_end:null});
 mocks.otp.mockResolvedValue({error:null});mocks.rpc.mockResolvedValue({error:null});
 mocks.generateLink.mockResolvedValue({data:{properties:{action_link:'https://example.supabase.co/auth/v1/verify?token=private'}},error:null});
 mocks.sendSecurityEmail.mockResolvedValue(undefined);
 mocks.notifySupportRequest.mockResolvedValue(undefined);mocks.notifyLeadFunnel.mockResolvedValue(undefined);mocks.notifyOperationalError.mockResolvedValue(undefined);
 mocks.answerPortalSupport.mockResolvedValue({answer:'Open Settings & billing to manage report recipients.',offerHuman:false});
 mocks.from.mockImplementation(table=>{
  if(['audit_admins','audit_portal_users'].includes(table))return{select:()=>({eq:()=>({maybeSingle:()=>Promise.resolve({data:table==='audit_admins'?(mocks.isAdmin?{user_id:'user-1'}:null):{enabled:mocks.enabled,guide_completed_at:mocks.guideCompletedAt},error:null})})})};
  if(table==='audit_portal_legal_acceptances'){const chain:any={eq:()=>chain,maybeSingle:()=>Promise.resolve({data:mocks.legalAcceptedAt?{accepted_at:mocks.legalAcceptedAt}:null,error:null})};return{select:()=>chain};}
  if(table==='audit_memberships')return{select:()=>({eq:()=>Promise.resolve({data:[{tenant_id:tenant,role:rose.role,audit_tenants:{id:tenant,name:'Company',alias:'company',status:'active'}}],error:null})})};
  if(table==='audit_rose_connections'){
   const chain:any={select:()=>chain,eq:()=>chain,maybeSingle:()=>Promise.resolve({data:rose.row,error:null}),insert:async(data:any)=>{rose.lastWrite=data;return {error:null};},update:(data:any)=>{rose.lastWrite=data;return chain;},then:(resolve:any)=>resolve({error:null})};
   return chain;
  }
  return mocks.query;
 });
 mocks.query.select.mockReturnValue(mocks.query);mocks.query.eq.mockReturnValue(mocks.query);mocks.query.gte.mockResolvedValue({data:[],count:0,error:null});mocks.query.order.mockReturnValue(mocks.query);mocks.query.range.mockResolvedValue({data:[],count:0,error:null});
 mocks.query.maybeSingle.mockResolvedValue({data:null,error:null});
 server=createApp({secret:'whsec_'+Buffer.from('test-secret-32-bytes-long-12345678').toString('base64'),enqueue:async()=>{},ready:async()=>true});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${(server.address() as any).port}`;
});
afterEach(async()=>{vi.unstubAllEnvs();vi.restoreAllMocks();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));});
const headers={'Content-Type':'application/json',Origin:'https://portal.example.com',Cookie:'audit_session=valid-token'};
it('serves login, mandatory legal acceptance, product guide and authenticated AI support with restrictive CSP',async()=>{const r=await fetch(base+'/');expect(r.status).toBe(200);expect(r.headers.get('content-security-policy')).toContain("frame-ancestors 'none'");const html=await r.text();expect(html).toContain('type="email"');expect(html).toContain('id="legal-acceptance"');expect(html).toContain('id="accept-terms"');expect(html).toContain('id="accept-privacy"');expect(html).toContain('id="product-guide"');expect(html).toContain('id="open-guide"');expect(html).toContain('id="open-support"');expect(html).toContain('id="support-panel"');});
it('hides customer workspace links while an administrator is managing accounts',async()=>{const page=await fetch(base+'/');const html=await page.text();expect(html).toContain('id="workspace-label"');expect(html).toContain('id="workspace-nav"');const admin=await fetch(base+'/admin.js');const script=await admin.text();expect(script).toContain('setWorkspaceNavigation(false)');expect(script).toContain('setWorkspaceNavigation(true)');});
it('renders jobs with the complete row instead of dereferencing a null error code',async()=>{const r=await fetch(base+'/dashboard.js');expect(r.status).toBe(200);const script=await r.text();expect(script).toContain('jobReason(r,r.result)');expect(script).not.toContain('jobReason(r.error_code)');});
it('serves a dedicated post-onboarding thank-you page',async()=>{const r=await fetch(base+'/onboarding/thanks');expect(r.status).toBe(200);const html=await r.text();expect(html).toContain('Thank you.');expect(html).toContain('Check your inbox.');});
it('rejects requests without a session before reading customer data',async()=>{const r=await fetch(base+'/api/portal/jobs?company='+tenant);expect(r.status).toBe(401);expect(mocks.from).not.toHaveBeenCalled();});
it('keeps portal AI support behind the authenticated company boundary',async()=>{const r=await fetch(base+'/api/portal/support?company='+tenant);expect(r.status).toBe(401);expect(mocks.answerPortalSupport).not.toHaveBeenCalled();expect(mocks.from).not.toHaveBeenCalled();});
it('answers portal support only after session and company access checks',async()=>{mocks.rpc.mockImplementation(async name=>name==='portal_support_open_conversation'?{data:{id:other,status:'ai'},error:null}:{data:{id:'message-1'},error:null});const body={messages:[{role:'user',content:'Where do I update report recipients?'}],context:{view:'settings'}};const r=await fetch(base+'/api/portal/support?company='+tenant,{method:'POST',headers,body:JSON.stringify(body)});expect(r.status).toBe(200);expect(await r.json()).toEqual({answer:'Open Settings & billing to manage report recipients.',offer_human:false,conversation_id:other,status:'ai'});expect(mocks.answerPortalSupport).toHaveBeenCalledWith(body);expect(mocks.rpc).toHaveBeenCalledWith('portal_support_append_message',expect.objectContaining({p_author_type:'customer',p_body:'Where do I update report recipients?'}));});
it('escalates a persisted conversation and alerts the dedicated support channel once',async()=>{mocks.rpc.mockImplementation(async name=>name==='portal_support_escalate'?{data:{id:other,notified_at:null,first_response_due_at:'2026-09-21T13:15:00.000Z',customer_name:'Client',customer_email:'client@example.com',escalation_problem:'I cannot resubmit this blocked invoice.'},error:null}:{data:null,error:null});const r=await fetch(base+`/api/portal/support/escalate?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({conversation_id:other,problem:'I cannot resubmit this blocked invoice.'})});expect(r.status).toBe(200);expect(await r.json()).toMatchObject({conversation_id:other,status:'waiting'});expect(mocks.notifySupportRequest).toHaveBeenCalledWith(expect.objectContaining({conversationId:other,email:'client@example.com',accountName:'Company',problem:'I cannot resubmit this blocked invoice.'}));expect(mocks.rpc).toHaveBeenCalledWith('portal_support_mark_notified',{p_conversation:other});});
it('rejects expired sessions',async()=>{mocks.getUser.mockResolvedValue({data:{user:null},error:{}});const r=await fetch(base+'/api/portal/me',{headers});expect(r.status).toBe(401);expect(mocks.from).not.toHaveBeenCalled();});
it('restores a returning customer from the long-lived refresh cookie',async()=>{
 mocks.refreshSession.mockResolvedValue({data:{user:{id:'user-1',email:'client@example.com'},session:{user:{id:'user-1',email:'client@example.com'},access_token:'renewed-access',refresh_token:'rotated-refresh'}},error:null});
 const r=await fetch(base+'/api/portal/me',{headers:{Cookie:'audit_refresh=existing-refresh'}});
 expect(r.status).toBe(200);expect(mocks.refreshSession).toHaveBeenCalledWith({refresh_token:'existing-refresh'});
 const cookies=r.headers.get('set-cookie')??'';expect(cookies).toContain('audit_session=renewed-access');expect(cookies).toContain('audit_refresh=rotated-refresh');
});
it('refreshes an expired access token without asking for another magic link',async()=>{
 mocks.getUser.mockResolvedValue({data:{user:null},error:{message:'expired'}});
 mocks.refreshSession.mockResolvedValue({data:{user:{id:'user-1',email:'client@example.com'},session:{user:{id:'user-1',email:'client@example.com'},access_token:'renewed-access',refresh_token:'rotated-refresh'}},error:null});
 const r=await fetch(base+'/api/portal/me',{headers:{Cookie:'audit_session=expired-token; audit_refresh=existing-refresh'}});
 expect(r.status).toBe(200);expect(mocks.refreshSession).toHaveBeenCalledTimes(1);
});
it('shows the guide on first login and hides it after completion',async()=>{let r=await fetch(base+'/api/portal/me',{headers});expect(r.status).toBe(200);expect(await r.json()).toMatchObject({show_guide:true});mocks.guideCompletedAt='2026-09-10T12:00:00.000Z';r=await fetch(base+'/api/portal/me',{headers});expect(await r.json()).toMatchObject({show_guide:false});});
it('requires current legal acceptance before customer onboarding and data access',async()=>{mocks.legalAcceptedAt=null;let r=await fetch(base+'/api/portal/me',{headers});expect(r.status).toBe(200);expect(await r.json()).toMatchObject({requires_legal_acceptance:true,terms_version:'2026-09-12',privacy_version:'2026-09-12',show_guide:true});r=await fetch(base+`/api/portal/jobs?company=${tenant}`,{headers});expect(r.status).toBe(428);expect(await r.json()).toEqual({error:'Accept the Terms of Service and acknowledge the Privacy Policy to continue.'});});
it('records authenticated portal acceptance with immutable evidence fields',async()=>{mocks.legalAcceptedAt=null;mocks.rpc.mockResolvedValue({data:'2026-09-12T18:30:00.000Z',error:null});const r=await fetch(base+'/api/portal/legal/accept',{method:'POST',headers:{...headers,'User-Agent':'Portal Test Browser'},body:JSON.stringify({terms_accepted:true,privacy_acknowledged:true})});expect(r.status).toBe(200);expect(await r.json()).toMatchObject({ok:true,terms_version:'2026-09-12',privacy_version:'2026-09-12'});expect(mocks.rpc).toHaveBeenCalledWith('record_portal_legal_acceptance',expect.objectContaining({p_user:'user-1',p_terms_version:'2026-09-12',p_privacy_version:'2026-09-12',p_acceptance_text:expect.stringContaining('authorized'),p_user_agent:'Portal Test Browser'}));});
it('does not allow the legal endpoint to record unchecked consent',async()=>{mocks.legalAcceptedAt=null;const r=await fetch(base+'/api/portal/legal/accept',{method:'POST',headers,body:JSON.stringify({terms_accepted:false,privacy_acknowledged:true})});expect(r.status).toBe(400);expect(mocks.rpc).not.toHaveBeenCalledWith('record_portal_legal_acceptance',expect.anything());});
it('records guide completion for the authenticated customer',async()=>{mocks.rpc.mockResolvedValue({data:'2026-09-10T12:00:00.000Z',error:null});const r=await fetch(base+'/api/portal/guide/complete',{method:'POST',headers,body:'{}'});expect(r.status).toBe(200);expect(await r.json()).toMatchObject({ok:true});expect(mocks.rpc).toHaveBeenCalledWith('portal_complete_guide');});
it('does not expose the customer guide action in administrator mode',async()=>{mocks.isAdmin=true;const r=await fetch(base+'/api/portal/guide/complete',{method:'POST',headers,body:'{}'});expect(r.status).toBe(403);expect(mocks.rpc).not.toHaveBeenCalledWith('portal_complete_guide');});
it('rejects cross-company reads',async()=>{const r=await fetch(base+'/api/portal/invoices?company='+other,{headers});expect(r.status).toBe(403);expect(mocks.from).not.toHaveBeenCalledWith('invoices');});
it('keeps Rose Rocket setup closed unless explicitly enabled',async()=>{
 const r=await fetch(base+`/api/portal/integrations/rose-rocket?company=${tenant}`,{method:'POST',headers,body:'{}'});
 expect(r.status).toBe(503);expect(mocks.from).not.toHaveBeenCalledWith('audit_rose_connections');
});
it('accepts only an owner or billing administrator for Rose Rocket setup',async()=>{
 vi.stubEnv('ROSE_ROCKET_CONNECT_ENABLED','true');rose.role='viewer';
 const r=await fetch(base+`/api/portal/integrations/rose-rocket?company=${tenant}`,{method:'POST',headers,body:'{}'});
 expect(r.status).toBe(403);expect(mocks.from).not.toHaveBeenCalledWith('audit_rose_connections');
});
it('verifies a Rose Rocket service account but stores it encrypted and disabled',async()=>{
 vi.stubEnv('ROSE_ROCKET_CONNECT_ENABLED','true');vi.stubEnv('ROSE_ROCKET_CREDENTIAL_KEY',Buffer.alloc(32,7).toString('base64url'));
 const verified=vi.spyOn(RoseRocketClient.prototype,'verifyAccess').mockResolvedValue();
 const r=await fetch(base+`/api/portal/integrations/rose-rocket?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({org_id:other,user_id:'33333333-3333-4333-8333-333333333333',client_id:'client-1',client_secret:'private-secret'})});
 expect(r.status).toBe(200);expect(await r.json()).toMatchObject({status:'pending',org_id:other});
 expect(verified).toHaveBeenCalledOnce();expect(rose.lastWrite).toMatchObject({org_id:other,tenant_id:tenant,connection_state:'pending',enabled:false});
 expect(rose.lastWrite.credentials_ciphertext).not.toContain('private-secret');
});
it('does not store Rose Rocket credentials when the provider rejects them',async()=>{
 vi.stubEnv('ROSE_ROCKET_CONNECT_ENABLED','true');
 vi.spyOn(RoseRocketClient.prototype,'verifyAccess').mockRejectedValue(new Error('ROSE_ACCESS_HTTP_403'));
 const r=await fetch(base+`/api/portal/integrations/rose-rocket?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({org_id:other,user_id:'33333333-3333-4333-8333-333333333333',client_id:'client-1',client_secret:'invalid-secret'})});
 expect(r.status).toBe(422);expect(rose.lastWrite).toBeNull();
});
it('disconnects Rose Rocket without exposing or deleting audit records',async()=>{
 const r=await fetch(base+`/api/portal/integrations/rose-rocket/disconnect?company=${tenant}`,{method:'POST',headers,body:'{}'});
 expect(r.status).toBe(200);expect(rose.lastWrite).toMatchObject({credentials_ciphertext:null,connected_at:null,enabled:false,connection_state:'disconnected'});
});
it('scopes and paginates every supported collection',async()=>{for(const collection of ['jobs','invoices','reports','exceptions','history']){const r=await fetch(base+`/api/portal/${collection}?company=${tenant}&page=2`,{headers});expect(r.status).toBe(200);expect(mocks.query.eq).toHaveBeenLastCalledWith('tenant_id',tenant);expect(mocks.query.range).toHaveBeenLastCalledWith(100,149);}});
it('normalizes an empty database result so the portal refresh remains renderable',async()=>{mocks.query.range.mockResolvedValueOnce({data:null,count:null,error:null});const r=await fetch(base+`/api/portal/jobs?company=${tenant}`,{headers});expect(r.status).toBe(200);expect(await r.json()).toEqual({rows:[],total:0,page:0});});
it('rejects cross-origin mutation',async()=>{const r=await fetch(base+'/api/portal/login',{method:'POST',headers:{...headers,Origin:'https://evil.example.com'},body:JSON.stringify({email:'client@example.com'})});expect(r.status).toBe(403);expect(mocks.otp).not.toHaveBeenCalled();});
it('requests passwordless login without creating accounts',async()=>{const r=await fetch(base+'/api/portal/login',{method:'POST',headers,body:JSON.stringify({email:'client@example.com'})});expect(r.status).toBe(200);expect(mocks.otp).toHaveBeenCalledWith({email:'client@example.com',options:{shouldCreateUser:false,emailRedirectTo:'https://portal.example.com/auth/callback'}});});
it('does not expose account existence',async()=>{mocks.otp.mockResolvedValue({error:{status:400}});const r=await fetch(base+'/api/portal/login',{method:'POST',headers,body:JSON.stringify({email:'missing@example.com'})});expect(await r.json()).toEqual({ok:true});});
it('resumes paid onboarding and emails one secure platform access button',async()=>{
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_paid',payment_status:'paid',status:'complete',customer:'cus_1',subscription:'sub_1',customer_details:{email:'owner@example.com'},metadata:{plan_code:'scale',billing_period:'annual'}});
 mocks.rpc.mockImplementation(async(name)=>name==='portal_onboarding_user_id'?{data:other,error:null}:name==='portal_complete_onboarding'?{data:{tenant_id:tenant,alias:'acme',audit_email:'acme@audit.aiolympian.com'},error:null}:name==='portal_save_notification_settings_v2'?{data:{pending_verification:[]},error:null}:{data:null,error:null});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_paid',company_name:'Acme Logistics',email:'owner@example.com',timezone:'America/Los_Angeles',report_emails:['owner@example.com']})});
 expect(response.status).toBe(200);expect(await response.json()).toMatchObject({audit_email:'acme@audit.aiolympian.com',access_email_sent:true});
 expect(mocks.createUser).not.toHaveBeenCalled();expect(mocks.generateLink).toHaveBeenCalledWith({type:'magiclink',email:'owner@example.com',options:{redirectTo:'https://portal.example.com/auth/callback'}});
 expect(mocks.sendSecurityEmail).toHaveBeenCalledWith(expect.objectContaining({to:'owner@example.com',subject:'Your Olympian account is ready',html:expect.stringContaining('Access the platform')}));
 expect(mocks.rpc).toHaveBeenCalledWith('sync_onboarding_billing_state',{p_session_id:'cs_test_paid',p_subscription_id:'sub_1',p_status:'active',p_trial_ends_at:null});
});
it('accepts a completed card-backed free trial and records its end date',async()=>{
 const trialEnd=Math.floor(Date.now()/1000)+86400;
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_trial',payment_status:'no_payment_required',status:'complete',customer:'cus_trial',subscription:'sub_trial',customer_details:{email:'owner@example.com'},metadata:{plan_code:'growth',billing_period:'monthly'}});
 mocks.retrieveSubscription.mockResolvedValue({id:'sub_trial',status:'trialing',customer:'cus_trial',trial_end:trialEnd});
 mocks.rpc.mockImplementation(async(name)=>name==='portal_onboarding_user_id'?{data:other,error:null}:name==='portal_complete_onboarding'?{data:{tenant_id:tenant,alias:'acme',audit_email:'acme@audit.aiolympian.com'},error:null}:name==='portal_save_notification_settings_v2'?{data:{pending_verification:[]},error:null}:{data:null,error:null});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_trial',company_name:'Acme Logistics',email:'owner@example.com',timezone:'America/Los_Angeles',report_emails:['owner@example.com']})});
 expect(response.status).toBe(200);
 expect(mocks.rpc).toHaveBeenCalledWith('sync_onboarding_billing_state',{p_session_id:'cs_test_trial',p_subscription_id:'sub_trial',p_status:'trialing',p_trial_ends_at:new Date(trialEnd*1000).toISOString()});
 expect(mocks.sendSecurityEmail).toHaveBeenCalledWith(expect.objectContaining({html:expect.stringContaining('free trial')}));
});
it('accepts a Stripe trial even when Checkout reports the saved card as paid',async()=>{
 const trialEnd=Math.floor(Date.now()/1000)+86400;
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_paid_trial',payment_status:'paid',status:'complete',customer:'cus_trial',subscription:'sub_trial',customer_details:{email:'owner@example.com'},metadata:{plan_code:'scale',billing_period:'semiannual'}});
 mocks.retrieveSubscription.mockResolvedValue({id:'sub_trial',status:'trialing',customer:'cus_trial',trial_end:trialEnd});
 mocks.rpc.mockImplementation(async(name)=>name==='portal_onboarding_user_id'?{data:other,error:null}:name==='portal_complete_onboarding'?{data:{tenant_id:tenant,alias:'acme',audit_email:'acme@audit.aiolympian.com'},error:null}:name==='portal_save_notification_settings_v2'?{data:{pending_verification:[]},error:null}:{data:null,error:null});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_paid_trial',company_name:'Acme Logistics',email:'owner@example.com',timezone:'America/Sao_Paulo',report_emails:['owner@example.com']})});
 expect(response.status).toBe(200);
 expect(mocks.rpc).toHaveBeenCalledWith('sync_onboarding_billing_state',{p_session_id:'cs_test_paid_trial',p_subscription_id:'sub_trial',p_status:'trialing',p_trial_ends_at:new Date(trialEnd*1000).toISOString()});
});
it('assigns the plan from the live Stripe subscription price instead of stale Checkout metadata',async()=>{
 vi.stubEnv('STRIPE_PRICE_SCALE_SEMIANNUAL','price_scale_six_months');const trialEnd=Math.floor(Date.now()/1000)+86400;
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_scale',payment_status:'paid',status:'complete',customer:'cus_trial',subscription:'sub_trial',customer_details:{email:'owner@example.com'},metadata:{plan_code:'core',billing_period:'monthly'}});
 mocks.retrieveSubscription.mockResolvedValue({id:'sub_trial',status:'trialing',customer:'cus_trial',trial_end:trialEnd,items:{data:[{price:{id:'price_scale_six_months'}}]}});
 mocks.rpc.mockImplementation(async(name)=>name==='portal_onboarding_user_id'?{data:other,error:null}:name==='portal_complete_onboarding'?{data:{tenant_id:tenant,alias:'acme',audit_email:'acme@audit.aiolympian.com'},error:null}:name==='portal_save_notification_settings_v2'?{data:{pending_verification:[]},error:null}:{data:null,error:null});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_scale',company_name:'Acme Logistics',email:'owner@example.com',timezone:'America/Sao_Paulo',report_emails:['owner@example.com']})});
 expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('assign_billing_plan',{p_tenant:tenant,p_plan:'scale',p_period:'semiannual',p_session_id:'cs_test_scale'});
});
it('loads the verified plan limit and checkout email for the onboarding form',async()=>{
 const trialEnd=Math.floor(Date.now()/1000)+86400;
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_context',payment_status:'paid',status:'complete',customer:'cus_trial',subscription:'sub_trial',customer_details:{email:'owner@example.com'},metadata:{plan_code:'core',billing_period:'monthly'}});
 mocks.retrieveSubscription.mockResolvedValue({id:'sub_trial',status:'trialing',customer:'cus_trial',trial_end:trialEnd});
 const response=await fetch(base+'/api/portal/onboarding/context?session_id=cs_test_context');
 expect(response.status).toBe(200);expect(await response.json()).toEqual({email:'owner@example.com',plan_code:'core',plan_name:'Core',max_recipients:3,trialing:true});
 expect(mocks.rpc).not.toHaveBeenCalled();
});
it('counts the checkout owner inside the plan recipient limit',async()=>{
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_limit',payment_status:'paid',status:'complete',customer:'cus_1',subscription:'sub_1',customer_details:{email:'owner@example.com'},metadata:{plan_code:'core',billing_period:'monthly'}});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_limit',company_name:'Acme',email:'owner@example.com',timezone:'UTC',report_emails:['one@example.com','two@example.com','three@example.com']})});
 expect(response.status).toBe(409);expect(await response.json()).toEqual({error:'The Core plan supports up to 3 report recipients.'});expect(mocks.rpc).not.toHaveBeenCalledWith('portal_complete_onboarding',expect.anything());
});
it('rejects a no-payment checkout that is not an active Stripe trial',async()=>{
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_free',payment_status:'no_payment_required',status:'complete',customer:'cus_1',subscription:'sub_1',customer_details:{email:'owner@example.com'},metadata:{plan_code:'core',billing_period:'monthly'}});
 mocks.retrieveSubscription.mockResolvedValue({id:'sub_1',status:'active',customer:'cus_1',trial_end:null});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_free',company_name:'Acme',email:'owner@example.com',timezone:'UTC',report_emails:['owner@example.com']})});
 expect(response.status).toBe(402);expect(mocks.rpc).not.toHaveBeenCalledWith('portal_complete_onboarding',expect.anything());
});
it('returns a resumable error when the identity lookup is not permitted',async()=>{
 mocks.retrieveCheckout.mockResolvedValue({id:'cs_test_paid',payment_status:'paid',status:'complete',customer:'cus_1',subscription:'sub_1',customer_details:{email:'owner@example.com'},metadata:{plan_code:'core',billing_period:'monthly'}});
 mocks.rpc.mockResolvedValueOnce({data:null,error:{code:'42501',message:'permission denied for table users'}});
 const response=await fetch(base+'/api/portal/onboarding',{method:'POST',headers,body:JSON.stringify({session_id:'cs_test_paid',company_name:'Acme',email:'owner@example.com',timezone:'UTC',report_emails:['owner@example.com']})});
 expect(response.status).toBe(503);expect(await response.json()).toEqual({error:'We could not finish setting up your account. Your payment is safe; please try again.'});expect(mocks.createUser).not.toHaveBeenCalled();
});
it('validates magic link token before creating strict HttpOnly sessions',async()=>{const token='x'.repeat(30);const r=await fetch(base+'/api/portal/session',{method:'POST',headers,body:JSON.stringify({access_token:token})});expect(r.status).toBe(200);expect(mocks.getUser).toHaveBeenCalledWith(token);expect(r.headers.get('set-cookie')).toContain('HttpOnly; SameSite=Strict; Path=/; Max-Age=3600; Secure');});
it('accepts Supabase magic links that explicitly omit a refresh token',async()=>{const token='x'.repeat(30);const r=await fetch(base+'/api/portal/session',{method:'POST',headers,body:JSON.stringify({access_token:token,refresh_token:null})});expect(r.status).toBe(200);expect(mocks.getUser).toHaveBeenCalledWith(token);});
it('rejects cross-company retry',async()=>{const r=await fetch(base+`/api/portal/jobs/${tenant}/retry?company=${other}`,{method:'POST',headers,body:JSON.stringify({note:'Review note'})});expect(r.status).toBe(403);expect(mocks.rpc).not.toHaveBeenCalled();});
it('requires review note and uses verified identity for atomic action',async()=>{const path=base+`/api/portal/jobs/${other}/review?company=${tenant}`;expect((await fetch(path,{method:'POST',headers,body:JSON.stringify({note:'x'})})).status).toBe(400);expect(mocks.rpc).not.toHaveBeenCalled();expect((await fetch(path,{method:'POST',headers,body:JSON.stringify({note:'Reviewed carrier details',user_id:'attacker'})})).status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_job_action',{p_user:'user-1',p_tenant:tenant,p_job:other,p_action:'review',p_note:'Reviewed carrier details'});});
it('reports stale job conflicts without leaking database details',async()=>{mocks.rpc.mockResolvedValue({error:{message:'private SQL'}});const r=await fetch(base+`/api/portal/jobs/${other}/review?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({note:'Reviewed details'})});expect(r.status).toBe(409);expect(await r.text()).not.toContain('private');});
it('records a confirmed avoided loss using the authenticated user',async()=>{const r=await fetch(base+`/api/portal/exceptions/${other}/resolve?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({outcome:'avoided',avoided_amount:875.25,note:'Duplicate charge canceled before payment'})});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_resolve_exception',{p_user:'user-1',p_tenant:tenant,p_exception:other,p_outcome:'avoided',p_avoided_amount:875.25,p_note:'Duplicate charge canceled before payment'});});
it('does not allow an avoided-loss claim without a confirmed amount',async()=>{const r=await fetch(base+`/api/portal/exceptions/${other}/resolve?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({outcome:'avoided',avoided_amount:null,note:'Charge reviewed by accounting'})});expect(r.status).toBe(400);expect(mocks.rpc).not.toHaveBeenCalledWith('portal_resolve_exception',expect.anything());});
it('saves recipients and senders without requiring authenticator enrollment',async()=>{vi.stubEnv('REQUIRE_MFA_SENSITIVE','true');const r=await fetch(base+`/api/portal/settings/notifications?company=${tenant}`,{method:'POST',headers,body:JSON.stringify({timezone:'America/Chicago',report_emails:['OPS@example.com','owner@example.com'],inbound_senders:['billing@example.com']})});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_save_security_settings',{p_tenant:tenant,p_timezone:'America/Chicago',p_contacts:expect.arrayContaining([expect.objectContaining({email:'ops@example.com',token_hash:expect.stringMatching(/^[a-f0-9]{64}$/)})]),p_senders:['billing@example.com'],p_ip_fingerprint:expect.any(String)});});
it('shows the private intake address using the plan synchronized by Stripe webhooks',async()=>{
 const original=mocks.from.getMockImplementation()!;
 mocks.from.mockImplementation(table=>{
  if(table==='audit_notification_settings')return{select:()=>({eq:()=>({maybeSingle:async()=>({data:{timezone:'America/Sao_Paulo',daily_hour:7},error:null})})})};
  if(table==='audit_report_contacts')return{select:()=>({eq:()=>({eq:()=>({order:async()=>({data:[{email:'owner@example.com',verified_at:'2026-09-10'}],error:null})})})})};
  if(table==='audit_billing_customers')return{select:()=>({eq:()=>({maybeSingle:async()=>({data:{billing_email:'client@example.com',stripe_subscription_id:'sub_scale',status:'trialing',plan_code:'core',billing_period:'monthly',included_invoices:500,overage_unit_amount_cents:75},error:null})})})};
  if(table==='audit_inbound_sender_rules')return{select:()=>({eq:()=>({eq:()=>({order:async()=>({data:[{sender_email:'owner@example.com'}],error:null})})})})};
  if(table==='audit_invoice_usage')return{select:()=>({eq:()=>({gte:async()=>({data:[],count:0,error:null})})})};
  return original(table);
 });
 const r=await fetch(base+`/api/portal/settings?company=${tenant}`,{headers});expect(r.status).toBe(200);const result=await r.json();expect(result.notifications).toMatchObject({audit_email:'company@audit.aiolympian.com',max_recipients:3,max_senders:1});expect(result.billing).toMatchObject({plan_code:'core',billing_period:'monthly',included_invoices:500,overage_unit_amount_cents:75});expect(mocks.retrieveSubscription).not.toHaveBeenCalled();expect(mocks.rpc).not.toHaveBeenCalledWith('sync_billing_plan_from_stripe',expect.anything());
});
it('does not let a non-owner change subscription billing',async()=>{mocks.query.maybeSingle.mockResolvedValue({data:{billing_email:'owner@example.com',stripe_customer_id:'cus_1',stripe_subscription_id:'sub_1',status:'active'},error:null});const r=await fetch(base+`/api/portal/billing/cancel?company=${tenant}`,{method:'POST',headers,body:'{}'});expect(r.status).toBe(403);expect(mocks.rpc).not.toHaveBeenCalledWith('portal_record_billing_action',expect.anything());});
it('clears session at logout',async()=>{const r=await fetch(base+'/api/portal/logout',{method:'POST',headers,body:'{}'});expect(r.headers.get('set-cookie')).toContain('Max-Age=0');});

it('reports a verified admin role without requiring company memberships',async()=>{mocks.isAdmin=true;const r=await fetch(base+'/api/portal/me',{headers});expect((await r.json()).is_admin).toBe(true);});
it('allows global admin to read another company with explicit scoping',async()=>{mocks.isAdmin=true;const r=await fetch(base+'/api/portal/invoices?company='+other,{headers});expect(r.status).toBe(200);expect(mocks.query.eq).toHaveBeenLastCalledWith('tenant_id',other);});
it('denies every administration route to customers',async()=>{for(const route of ['companies','users','confidence','activity','action']){const r=await fetch(base+'/api/portal/admin/'+route,{headers});expect(r.status).toBe(403);}expect(mocks.rpc).not.toHaveBeenCalled();});
it('rejects disabled users even when their token remains valid',async()=>{mocks.isAdmin=true;mocks.enabled=false;const r=await fetch(base+'/api/portal/admin/companies',{headers});expect(r.status).toBe(401);expect(mocks.rpc).not.toHaveBeenCalled();});
it('ignores forged admin flags in the request body',async()=>{const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'company.create',name:'Acme',alias:'acme',is_admin:true})});expect(r.status).toBe(403);expect(mocks.rpc).not.toHaveBeenCalled();});
it('rejects cross-origin admin changes',async()=>{mocks.isAdmin=true;const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers:{...headers,Origin:'https://evil.example.com'},body:'{}'});expect(r.status).toBe(403);});
it('passes only validated company fields and verified actor to the transaction',async()=>{mocks.isAdmin=true;const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'company.create',name:'Acme',alias:'acme',p_actor:other,status:'active'})});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_admin_action',{p_actor:'user-1',p_action:'company.create',p_payload:{name:'Acme',alias:'acme'}});});
it('validates aliases and membership UUIDs before mutations',async()=>{mocks.isAdmin=true;for(const payload of [{action:'company.create',name:'Acme',alias:'../evil'},{action:'membership.add',user_id:'invalid',company_id:tenant},{action:'user.role',user_id:other,role:'owner'}]){const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify(payload)});expect(r.status).toBe(400);}expect(mocks.rpc).not.toHaveBeenCalled();});
it('uses paginated scoped user RPC without listing unrelated Auth users',async()=>{mocks.isAdmin=true;mocks.rpc.mockResolvedValue({data:{rows:[],total:0,page:2},error:null});const r=await fetch(base+'/api/portal/admin/users?page=2',{headers});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_admin_users',{p_actor:'user-1',p_page:2});});
it('loads the paginated quality-control sample for administrators',async()=>{mocks.isAdmin=true;mocks.rpc.mockResolvedValue({data:{rows:[],total:0,page:1},error:null});const r=await fetch(base+'/api/portal/admin/confidence?page=1',{headers});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_admin_confidence_reviews',{p_actor:'user-1',p_page:1});});
it('lets an administrator list, open and reply to support conversations',async()=>{mocks.isAdmin=true;mocks.rpc.mockImplementation(async name=>name==='portal_admin_support_queue'?{data:{rows:[{id:other,status:'waiting'}],total:1,page:0},error:null}:name==='portal_admin_support_conversation'?{data:{conversation:{id:other,status:'waiting'},messages:[]},error:null}:{data:{id:'message-1',body:'We are checking this now.'},error:null});let r=await fetch(base+'/api/portal/admin/support',{headers});expect(r.status).toBe(200);expect(await r.json()).toMatchObject({total:1});r=await fetch(base+`/api/portal/admin/support/${other}`,{headers});expect(r.status).toBe(200);r=await fetch(base+`/api/portal/admin/support/${other}/reply`,{method:'POST',headers,body:JSON.stringify({message:'We are checking this now.'})});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_admin_support_reply',{p_actor:'user-1',p_conversation:other,p_body:'We are checking this now.'});});
it('records a validated confidence review with the verified administrator',async()=>{mocks.isAdmin=true;mocks.rpc.mockResolvedValue({data:null,error:null});const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'confidence.review',id:other,result:'corrected',corrected_fields:{valor_total:1250},p_actor:'attacker'})});expect(r.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith('portal_admin_review_confidence',{p_actor:'user-1',p_review:other,p_result:'corrected',p_corrected_fields:{valor_total:1250}});});
it('checks target company before provisioning user',async()=>{mocks.isAdmin=true;const original=mocks.from.getMockImplementation()!;mocks.from.mockImplementation(table=>table==='audit_tenants'?{select:()=>({eq:()=>({maybeSingle:async()=>({data:null,error:null})})})}:original(table));const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'user.create',email:'new@example.com',company_id:tenant})});expect(r.status).toBe(409);expect(mocks.createUser).not.toHaveBeenCalled();});
it('provisions without sending an email and assigns access transactionally',async()=>{mocks.isAdmin=true;const original=mocks.from.getMockImplementation()!;mocks.from.mockImplementation(table=>table==='audit_tenants'?{select:()=>({eq:()=>({maybeSingle:async()=>({data:{id:tenant},error:null})})})}:original(table));mocks.rpc.mockResolvedValue({data:null,error:null});mocks.createUser.mockResolvedValue({data:{user:{id:other}},error:null});const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'user.create',email:'NEW@example.com',company_id:tenant})});expect(r.status).toBe(200);expect(mocks.createUser).toHaveBeenCalledWith({email:'new@example.com',email_confirm:false});expect(mocks.rpc).toHaveBeenLastCalledWith('portal_admin_action',{p_actor:'user-1',p_action:'user.register',p_payload:{user_id:other,company_id:tenant}});});
it('reuses an existing identity instead of creating a duplicate',async()=>{mocks.isAdmin=true;const original=mocks.from.getMockImplementation()!;mocks.from.mockImplementation(table=>table==='audit_tenants'?{select:()=>({eq:()=>({maybeSingle:async()=>({data:{id:tenant},error:null})})})}:original(table));mocks.rpc.mockResolvedValue({data:other,error:null});const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'user.create',email:'existing@example.com',company_id:tenant})});expect(r.status).toBe(200);expect(mocks.createUser).not.toHaveBeenCalled();});
it('hides internal errors from admin action failures',async()=>{mocks.isAdmin=true;mocks.rpc.mockResolvedValue({error:{message:'private database details'}});const r=await fetch(base+'/api/portal/admin/action',{method:'POST',headers,body:JSON.stringify({action:'user.role',user_id:other,role:'admin'})});expect(r.status).toBe(409);expect(await r.text()).not.toContain('private database');});
