import { readFile } from 'node:fs/promises';
import { createHash, randomUUID } from 'node:crypto';
import type { IExtractionProvider } from '../extraction/extraction.interface.js';
import type { GetCarrierFn, RuleException } from '../types/rule.types.js';
import type { AuditContext } from '../types/carrier.types.js';
import type { InvoiceRecord } from '../types/invoice.types.js';
import type { AuditReport } from '../types/report.types.js';
import { normalizeFields } from '../normalization/index.js';
import { createAuditStore, type AuditStore } from '../db/audit.repo.js';
import { ALL_RULES } from '../rules/index.js';
import { buildReport } from '../report/report.builder.js';

export interface PipelineOptions {
  tenantId: string;
  filePaths: string[];
  sourceLabels?: Record<string,string>;
  ctx: AuditContext;
  extractor: IExtractionProvider;
  getCarrier: GetCarrierFn;
  store?: AuditStore;
  minimumInvoiceDate?: string;
  maximumInvoiceDate?: string;
}

export async function runAuditPipeline(options: PipelineOptions): Promise<AuditReport> {
  const { filePaths, ctx, extractor, getCarrier, tenantId, store = createAuditStore(options.tenantId) } = options;
  await store.assertActive();
  const history = await store.history();
  if (history.some(i => i.tenant_id !== tenantId)) throw new Error('Cross-account history rejected.');
  const known = new Set(history.map(inv => inv.document_hash).filter(Boolean));
  const invoices: InvoiceRecord[] = [];
  const skipped: string[] = [];
  for (const file of filePaths) {
    const bytes = await readFile(file);
    if (!bytes.subarray(0, 1024).includes(Buffer.from('%PDF-'))) throw new Error(`Not a PDF: ${file}`);
    const hash = createHash('sha256').update(bytes).digest('hex');
    if (known.has(hash)) { skipped.push(options.sourceLabels?.[file] ?? file); continue; }
    await store.assertActive();
    const result = await extractor.extract(file);
    // Detect modification during extraction before attaching a content identity.
    if (createHash('sha256').update(await readFile(file)).digest('hex') !== hash) throw new Error(`File changed during extraction: ${file}`);
    const fields = normalizeFields(result.fields);
    const documentDate = fields.data_fatura ?? fields.data_carga;
    if (documentDate && ((options.minimumInvoiceDate && documentDate < options.minimumInvoiceDate) || (options.maximumInvoiceDate && documentDate > options.maximumInvoiceDate))) {
      skipped.push(options.sourceLabels?.[file] ?? file);
      continue;
    }
    const confidence = { ...result.confidence_scores };
    for (const key of ['data_carga', 'data_fatura'] as const) {
      if (result.fields[key] && !fields[key]) confidence[key] = 0;
    }
    invoices.push({ ...fields, tenant_id: tenantId, id: randomUUID(), source_file: options.sourceLabels?.[file] ?? file, document_hash: hash,
      numero_fatura: fields.numero_fatura ?? '', confidence_scores: confidence,
      accessorials: result.accessorials, extraction_raw: result.extraction_raw, created_at: new Date().toISOString() });
    known.add(hash);
  }
  const currentIds = new Set(invoices.map(inv => inv.id));
  const exceptions: RuleException[] = [];
  const historicalRules = new Set(['DUPLICATE_EXACT', 'DUPLICATE_PROBABLE', 'BANKING_CHANGE']);
  if (invoices.length) for (const rule of ALL_RULES) {
    const input = historicalRules.has(rule.name) ? [...history, ...invoices] : invoices;
    exceptions.push(...(await rule.evaluate(input, getCarrier, ctx)).filter(ex => currentIds.has(ex.invoice_id)));
  }
  const report = buildReport(invoices, exceptions, ctx);
  report.tenant_id = tenantId;
  report.skipped_files = skipped;
  report.warnings = ['Carrier checks describe lookup-time status; historical load-date authority is not verified.'];
  if (invoices.some(inv => inv.extraction_raw.provider === 'stub')) report.warnings.push('SIMULATION: invoice fields were generated by the stub extractor.');
  if (invoices.some(inv => inv.extraction_raw.provider === 'openrouter')) report.warnings.push('OpenRouter extraction requires human review; confidence scores are conservative placeholders, not calibrated probabilities.');
  if (process.env.CARRIER_PROVIDER !== 'fmcsa') report.warnings.push('SIMULATION: carrier provider is not configured for live FMCSA data.');
  if (invoices.length) await store.assertActive();
  if (invoices.length) await store.commit(invoices, exceptions, report, history.map(inv => inv.id));
  return report;
}
