import {describe,expect,it} from 'vitest';
import {failureEmail,freeAuditCsv,freeAuditPdf,repeatOfferEmail,resultEmail,verificationEmail} from '../../src/free-audit/artifacts.js';
const report={run_id:'11111111-1111-4111-8111-111111111111',generated_at:new Date().toISOString(),total_invoices_processed:2,total_exceptions:1,valor_total_under_review:900,exceptions:[{invoice_id:'i1',tipo_regra:'DUPLICATE_EXACT',rule_label:'Exact Duplicate Invoice',valor_envolvido:900,descricao:'Duplicate',source_reference:{file:'invoice.pdf',page:1},metadata:{}}]};
describe('free audit email artifacts',()=>{
 it('uses one result CTA instead of selling plans in the email',()=>{expect(verificationEmail('Alex','https://example.com/verify').html).toContain('Confirm and start');expect(repeatOfferEmail('Alex','https://example.com/plans').html).toContain('See plans');const result=resultEmail('Alex','Acme',report,'https://portal.example.com');expect(result.html).toContain('View my audit');expect(result.html).not.toContain('Choose a plan');expect(result.html).not.toContain('Core');expect(result.html).not.toContain('Scale');expect(result.html).toContain('https://portal.example.com');});
 it('keeps finding details on the private result and downloadable files',()=>{const result=resultEmail('Alex','Acme',report,'https://portal.example.com');expect(result.html).toContain('private link expires');expect(result.html).not.toContain('Exact Duplicate Invoice');expect(result.html).not.toContain('Duplicate</');});
 it('links processing failures to file-only recovery without exposing internals',()=>{const email=failureEmail('Alex','invalid_document','https://example.com/retry?token=safe');expect(email.subject).toContain('Action needed');expect(email.html).toContain('standard, unencrypted PDF');expect(email.html).toContain('Upload replacement files');expect(email.html).toContain('contact details are saved');expect(email.html).not.toContain('stack');});
 it('generates a structured visual PDF and usable CSV attachment',()=>{const pdf=freeAuditPdf('Acme',report);const source=pdf.toString('ascii');expect(pdf.subarray(0,8).toString()).toBe('%PDF-1.4');expect(source).toContain('AUDIT SNAPSHOT');expect(source).toContain('AMOUNT UNDER REVIEW');expect(source).toContain('FINDINGS REQUIRING REVIEW');expect(source).toContain('Exact Duplicate Invoice');expect(source).toContain('Page 1 of 1');expect(freeAuditCsv(report).toString()).toContain('Exact Duplicate Invoice');});
 it('paginates long reports without losing the review disclaimer',()=>{const longReport={...report,total_exceptions:18,exceptions:Array.from({length:18},(_,index)=>({...report.exceptions[0],invoice_id:`i${index}`,descricao:'A detailed explanation that remains readable and wraps into more than one line in the visual report.'}))};const source=freeAuditPdf('Acme',longReport).toString('ascii');expect(source).toMatch(/\/Count [2-9]/);expect(source).toContain('Page 2 of');expect(source.match(/Automated findings require human review/g)?.length).toBeGreaterThan(1);});
});
