import {describe,expect,it} from 'vitest';
import {failureEmail,freeAuditCsv,freeAuditPdf,repeatOfferEmail,resultEmail,verificationEmail} from '../../src/free-audit/artifacts.js';
const report={run_id:'11111111-1111-4111-8111-111111111111',generated_at:new Date().toISOString(),total_invoices_processed:2,total_exceptions:1,valor_total_under_review:900,exceptions:[{invoice_id:'i1',tipo_regra:'DUPLICATE_EXACT',rule_label:'Exact Duplicate Invoice',valor_envolvido:900,descricao:'Duplicate',source_reference:{file:'invoice.pdf',page:1},metadata:{}}]};
describe('free audit email artifacts',()=>{
 it('includes confirmation and commercial calls to action',()=>{expect(verificationEmail('Alex','https://example.com/verify').html).toContain('Confirm and start');expect(repeatOfferEmail('Alex','https://example.com/plans').html).toContain('See plans');const result=resultEmail('Alex','Acme',report,'https://portal.example.com');expect(result.html).toContain('Choose a plan and subscribe');expect(result.html).toContain('Core');expect(result.html).toContain('Scale');expect(result.html).toContain('https://portal.example.com');});
 it('keeps finding details in the PDF and CSV instead of the email body',()=>{const result=resultEmail('Alex','Acme',report,'https://portal.example.com');expect(result.html).toContain('complete audit is attached');expect(result.html).not.toContain('Exact Duplicate Invoice');expect(result.html).not.toContain('Duplicate</');});
 it('links processing failures to file-only recovery without exposing internals',()=>{const email=failureEmail('Alex','invalid_document','https://example.com/retry?token=safe');expect(email.subject).toContain('Action needed');expect(email.html).toContain('standard, unencrypted PDF');expect(email.html).toContain('Upload replacement files');expect(email.html).toContain('contact details are saved');expect(email.html).not.toContain('stack');});
 it('generates usable private report attachments',()=>{expect(freeAuditPdf('Acme',report).subarray(0,8).toString()).toBe('%PDF-1.4');expect(freeAuditCsv(report).toString()).toContain('Exact Duplicate Invoice');});
});
