export const TERMS_VERSION='2026-09-12';
export const PRIVACY_VERSION='2026-09-12';
export const PORTAL_ACCEPTANCE_TEXT='I have read and agree to the Terms of Service and acknowledge the Privacy Policy. I confirm that I am authorized to accept these terms on behalf of my company.';

export function legalPage(kind:'terms'|'privacy'){
 const terms=kind==='terms';
 return `<main class="legal"><span class="eyebrow">Legal</span><h1>${terms?'Terms of Service':'Privacy Policy'}</h1><p class="legal-meta">Effective September 12, 2026 · Version ${terms?TERMS_VERSION:PRIVACY_VERSION}</p>${terms?termsBody():privacyBody()}</main>`;
}

function termsBody(){return `
<section><h2>1. Agreement and business use</h2><p>These Terms govern access to Olympian's freight invoice auditing service. By creating an account, starting a trial, or purchasing a subscription, you confirm that you are authorized to bind the business you represent and agree to these Terms and our Privacy Policy. The service is intended for business use by adults.</p></section>
<section><h2>2. The service and customer decisions</h2><p>Olympian analyzes invoices and supporting freight documents to identify possible duplicates, carrier-status issues, banking changes, charge discrepancies, and other exceptions. Results are decision-support information, not accusations, legal advice, payment instructions, or a guarantee that every error or fraud attempt will be detected. You remain responsible for reviewing exceptions and making payment, carrier, and operational decisions.</p></section>
<section><h2>3. Accounts and permitted use</h2><p>You must provide accurate information, protect access links and credentials, and use only documents you are authorized to process. You may not misuse the service, interfere with security, reverse engineer protected components, upload unlawful content, or use results to make unlawful or discriminatory decisions.</p></section>
<section><h2>4. Customer data</h2><p>You retain ownership of your data. You grant Olympian the limited rights needed to host, analyze, secure, and transmit it to provide the service. You represent that you have the rights and notices required to submit personal, financial, carrier, and shipment information. Submitted documents are ordinarily deleted within 30 days, while transaction, security, legal-consent, and audit records may be retained longer when needed for the service, compliance, disputes, or fraud prevention.</p></section>
<section><h2>5. Trials, fees, renewal, and cancellation</h2><p>The checkout page states the trial length, price, and billing frequency that apply to your selection. Unless you cancel before the 7-day trial ends, Stripe will charge the payment method on file and the subscription will automatically renew at the displayed cadence until canceled. You can cancel through the billing controls in the customer portal; cancellation prevents future renewals and does not normally refund charges already incurred, except where law requires otherwise. Taxes and usage overages may apply as disclosed at checkout.</p></section>
<section><h2>6. Availability and changes</h2><p>We work to keep the service reliable but do not promise uninterrupted or error-free operation unless a separate written service-level agreement says otherwise. We may improve or change features while preserving the material function of a paid plan. Third-party services, including payment, email, storage, AI, and public carrier-data providers, may affect availability.</p></section>
<section><h2>7. Confidentiality and security</h2><p>Each party will protect the other's confidential information using reasonable care. Olympian uses administrative and technical safeguards designed to protect customer data, but no system is completely secure. You must notify us promptly of suspected unauthorized access.</p></section>
<section><h2>8. Intellectual property</h2><p>Olympian and its licensors own the service, software, designs, and documentation. Except for the limited right to use the service during your subscription, no rights are transferred to you. Feedback may be used without restriction or payment.</p></section>
<section><h2>9. Disclaimers and liability</h2><p>To the maximum extent permitted by law, the service is provided “as is” and implied warranties are disclaimed. Neither party is liable for indirect, special, incidental, exemplary, or consequential damages. Olympian's aggregate liability relating to the service will not exceed the fees you paid for the service during the 12 months before the event giving rise to the claim. These limits do not apply where the law does not permit them.</p></section>
<section><h2>10. Suspension and termination</h2><p>We may suspend access for nonpayment, security risk, unlawful use, or a material breach. You may stop using the service and cancel renewal at any time. Provisions that by their nature should survive termination will survive.</p></section>
<section><h2>11. Updates, governing terms, and contact</h2><p>Material updates will be presented with a new version and, when required, a new acceptance. Any order form or signed agreement controls if it expressly conflicts with these Terms. Questions or legal notices may be sent to <a href="mailto:support@aiolympian.com">support@aiolympian.com</a>. The governing law and forum must be stated in the applicable order form until Olympian publishes its legal entity and principal business jurisdiction here.</p></section>`;}

function privacyBody(){return `
<section><h2>1. Scope</h2><p>This Policy explains how Olympian handles information through its websites, checkout, customer portal, invoice-auditing service, and support channels. It does not cover a customer's own privacy practices.</p></section>
<section><h2>2. Information we collect</h2><p>We collect account and contact details; company, plan, and subscription information; billing identifiers supplied by Stripe (not full card numbers); invoices, rate confirmations, PODs, banking details, carrier identifiers, shipment and load information; recipient and sender addresses; support communications; and device, browser, IP, security, access, and usage records. We also retain evidence of legal acceptance, including the authenticated user, wording and versions presented, date and time, IP address, and user agent.</p></section>
<section><h2>3. How we use information</h2><p>We use information to provide and secure the service, audit documents, match supporting records, send reports and alerts, manage billing and accounts, prevent abuse, troubleshoot, comply with law, and improve reliability. We do not sell personal information or share it for cross-context behavioral advertising.</p></section>
<section><h2>4. Service providers and disclosures</h2><p>Information may be processed by providers that help operate the service, such as Supabase, Cloudflare, Stripe, Resend, AI model providers, and government carrier-data services such as FMCSA. We may also disclose information when required by law, to protect rights and security, during a corporate transaction, or at your direction. Providers receive only the access reasonably needed for their role and are subject to applicable contractual restrictions.</p></section>
<section><h2>5. Retention</h2><p>Submitted audit documents are ordinarily deleted within 30 days. We keep account, billing, security, consent, transaction, and audit records only as long as reasonably needed for the purposes described above, legal obligations, fraud prevention, and dispute resolution. Backups may take additional time to expire.</p></section>
<section><h2>6. Security and international processing</h2><p>We use safeguards designed to protect information in transit, at rest, and across customer workspaces. Information may be processed in the United States and other countries where our providers operate, subject to applicable transfer protections. No security measure can eliminate all risk.</p></section>
<section><h2>7. Your choices and U.S. state rights</h2><p>You may request access, correction, or deletion of account information and may unsubscribe from non-essential messages. Depending on your state and whether its law applies to Olympian, you may also have rights to know, correct, delete, obtain a copy, opt out of certain uses, limit certain sensitive-data uses, appeal a decision, and receive equal service. We will verify requests and may retain information when legally permitted. Authorized agents may submit requests where allowed.</p></section>
<section><h2>8. Children</h2><p>The service is for businesses and is not directed to children under 13. We do not knowingly collect children's personal information.</p></section>
<section><h2>9. Changes and contact</h2><p>We may update this Policy and will change the effective date and version when we do. Material changes will be communicated or presented for renewed acknowledgment when required. Privacy requests and questions may be sent to <a href="mailto:support@aiolympian.com">support@aiolympian.com</a>.</p></section>`;}
