import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {OpenRouterPodExtractor} from '../../src/pod/openrouter.extractor.js';
const evidence={page:1,text:'Signed by Ana',bounding_box:{x:0.1,y:0.2,width:0.3,height:0.1}};const field=(value:unknown,confidence=0.98)=>({value,confidence,evidence:value==null?null:evidence});
const payload={fields:{load_number:field('L-1'),bol_number:field('B-1'),delivery_date:field('2026-09-08'),delivery_time:field('10:30'),receiver_name:field('Ana'),delivery_location:field('Miami'),signature_present:field(true),damage_or_shortage_noted:field(false),exception_notes:field(null,0)},quality:{score:0.93,rotation_degrees:0,perspective_distortion:false,blur:false,glare_or_shadow:false,cropped:false,reasons:[]}};
let dir:string;beforeEach(async()=>{vi.stubEnv('OPENROUTER_API_KEY','secret');vi.stubEnv('POD_OPENROUTER_MODEL','test/model');dir=await mkdtemp(join(tmpdir(),'pod-'));});afterEach(async()=>{vi.unstubAllEnvs();await rm(dir,{recursive:true,force:true});});
describe('OpenRouter POD extraction',()=>{
 it('sends an image with strict schema and retains evidence',async()=>{const file=join(dir,'pod.jpg');await writeFile(file,Buffer.from([0xff,0xd8,0xff]));const request=vi.fn().mockResolvedValue(Response.json({id:'r1',model:'test/model',choices:[{finish_reason:'stop',message:{content:JSON.stringify(payload)}}]}));const pod=await new OpenRouterPodExtractor(request).extract(file);expect(pod.fields.signature_present.value).toBe(true);expect(pod.fields.receiver_name.evidence?.page).toBe(1);expect(pod.requires_human_review).toBe(false);const body=JSON.parse(request.mock.calls[0][1].body);expect(body.messages[1].content[1].file.file_data).toContain('data:image/jpeg;base64,');expect(body.response_format.json_schema.strict).toBe(true);});
 it('requires review for a low-confidence present field',async()=>{const file=join(dir,'pod.pdf');await writeFile(file,'%PDF-1.4');const low=structuredClone(payload);low.fields.receiver_name.confidence=0.5;const request=vi.fn().mockResolvedValue(Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(low)}}]}));expect((await new OpenRouterPodExtractor(request).extract(file)).requires_human_review).toBe(true);});
 it('rejects unsupported files and invalid provider output',async()=>{const file=join(dir,'pod.txt');await writeFile(file,'x');await expect(new OpenRouterPodExtractor(vi.fn()).extract(file)).rejects.toThrow('Unsupported');const image=join(dir,'pod.png');await writeFile(image,Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));await expect(new OpenRouterPodExtractor(vi.fn().mockResolvedValue(Response.json({choices:[]}))).extract(image)).rejects.toThrow('invalid extraction');});
});
