services:
  better-stack-vector:
    image: timberio/vector:latest-alpine
    environment:
      BETTER_STACK_INGESTING_HOST: ${BETTER_STACK_INGESTING_HOST}
      BETTER_STACK_SOURCE_TOKEN: ${BETTER_STACK_SOURCE_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - better-stack-vector-data:/var/lib/vector
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    mem_limit: 192m
    cpus: 0.5
    pids_limit: 100

volumes:
  better-stack-vector-data:
